#Spring configuration
server:
  port: 8081
  servlet:
    context-path: /data-generator

##Eureka configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}

#Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health

#Zipkin configuration
spring:
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL}
